# Generated by Django 5.0.6 on 2024-05-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_phoneimages_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonelist',
            name='colors',
        ),
    ]
