# Generated by Django 5.0.6 on 2024-06-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_phonelist_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneimages',
            name='color',
        ),
    ]
