# Generated by Django 5.0.6 on 2024-06-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_phonelist_price_phoneimages_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonelist',
            name='additional',
        ),
        migrations.AddField(
            model_name='phonelist',
            name='country_of_origin',
            field=models.CharField(default='India', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonelist',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdditionalDetails',
        ),
    ]
