# Generated by Django 5.0.6 on 2024-06-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_phonelist_additional_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.RemoveField(
            model_name='phonelist',
            name='front_camera',
        ),
        migrations.RemoveField(
            model_name='rearcamera',
            name='features',
        ),
        migrations.RemoveField(
            model_name='phonelist',
            name='rear_camera',
        ),
        migrations.AlterField(
            model_name='display',
            name='brightness',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='color_depth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='hz',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='pixel_per_inch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='display',
            name='touch_response',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FrontCamera',
        ),
        migrations.DeleteModel(
            name='RearCamera',
        ),
    ]
