# Generated by Django 5.0.6 on 2024-06-03 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_color_remove_phonelist_front_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameradetails',
            old_name='camera_mp',
            new_name='camera_megapixel',
        ),
        migrations.RemoveField(
            model_name='phonelist',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='phonelist',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='phonelist',
            name='display',
        ),
        migrations.RemoveField(
            model_name='phonelist',
            name='os_details',
        ),
        migrations.AddField(
            model_name='phonelist',
            name='battery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.batterydetails'),
        ),
        migrations.AddField(
            model_name='phonelist',
            name='cpu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.cpuspecs'),
        ),
        migrations.AddField(
            model_name='phonelist',
            name='display',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.display'),
        ),
        migrations.AddField(
            model_name='phonelist',
            name='os_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.osdetails'),
        ),
    ]
