# Generated by Django 5.0.6 on 2024-06-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_camera_mp_cameradetails_camera_megapixel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneimages',
            name='price',
        ),
        migrations.AddField(
            model_name='ramrom',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
