# Generated by Django 5.0.6 on 2024-06-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_phoneimages_price_ramrom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramrom',
            name='price',
        ),
        migrations.AddField(
            model_name='phoneimages',
            name='price_to_add',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonelist',
            name='original_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ramrom',
            name='price_to_add',
            field=models.IntegerField(default=0),
        ),
    ]
