# Generated by Django 5.0.6 on 2024-06-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_ramrom_price_phoneimages_price_to_add_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='display_name',
            field=models.CharField(max_length=60),
        ),
    ]
