# Generated by Django 5.0.6 on 2024-07-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_address_district_alter_address_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorders',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cart', to='products.cart'),
        ),
    ]
