# Generated by Django 5.0.6 on 2024-07-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_placedorders_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorders',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='address', to='products.address'),
        ),
    ]
